

services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://16.176.49.239:5000/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend